natalcare/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nc.urls')),
]

nc/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

urlpatterns = [
    path('cadastro/', cadastrousuario.as_view(), name='cadastro'),
    path('procadu/', cadastrousuario.as_view(), name='procadu'),
    path('procadc/', cadastroclinica.as_view(), name='procadc'),
    path('login/', logusuario.as_view(), name='log'),
    path('prologu/', logusuario.as_view(), name='prologu'),
    path('prologc/', logclinica.as_view(), name='prologc'),
    path('', menu.as_view(), name='menu'),
    path('perfil/', perfil.as_view(), name="perfil"),
    path('properfil/', perfil.as_view(), name="properfil"),
    path('pesq/', resultados.as_view(), name="pesq"),
    path('logoutu/', logoutu.as_view(), name="logoutu"),
    path('msc/', mudar_senha_clin.as_view(), name="msc"),
    path('promsc/', mudar_senha_clin.as_view(), name="promsc"),
    path('clinc/', clin_dados.as_view(), name="clinc"),
    path('clinu/<int:id>/', clinusu.as_view(), name="clinu"),
    path('clined/', clinedit.as_view(), name="clined"),
    path('proclined/', clinedit.as_view(), name="proclined"),
    path('coment/<int:id>/', comentario.as_view(), name="coment"),
    path('favs/<int:id>/', favoritos.as_view(), name="favs"),
    path('prochatusu/<int:id>/', prochatusu.as_view(), name="prochatusu"),
    path('chatusu/', chatusu.as_view(), name="chatusu"),
    path('chatclin/', chatclin.as_view(), name="chatclin"),
    path('prochatclin/<int:id>', prochatclin.as_view(), name="prochatclin"),
]

nc/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

# Create your models here.

class especialidades(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class plano(models.Model):
    nome = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='planos', blank=True)

    def __str__(self):
        return self.nome

class endereco(models.Model):
    logradouro = models.CharField(max_length=100)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=9)
    complemento = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.logradouro}, {self.numero}, {self.complemento + ','  if self.complemento  else ''} {self.bairro} - {self.cep}, {self.cidade}/{self.estado}"

class clinica(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=18, unique=True)
    telefone = models.CharField(max_length=14)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=10)
    endereco = models.OneToOneField(endereco, on_delete=models.CASCADE)
    plano = models.ManyToManyField(plano, blank=True)
    especialidades = models.ManyToManyField(especialidades, blank=True)
    foto = models.ImageField(blank=True, null=True, default="batmanresolveintherain.jpg", upload_to="perfil_clin/")
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.nome
    
class usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14, unique=True)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=10)
    telefone = models.CharField(max_length=15)
    endereco = models.OneToOneField(endereco, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class historico(models.Model):
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['data']
        unique_together = ['usuario', 'clinica']

    def __str__(self):
        return f"{self.usuario.nome} -> {self.clinica.nome}"

class favorito(models.Model):
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['data']
        unique_together = ['usuario', 'clinica']

    def __str__(self):
        return f"{self.usuario.nome} -> {self.clinica.nome}"
    
class comentarios(models.Model):
    comentario = models.TextField()
    avaliacao = models.BooleanField()
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)

    def __str__(self):
        return self.comentario

class chat(models.Model):
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.usuario.nome} -> {self.clinica.nome}"

class mensagens(models.Model):
    mensagem = models.TextField()
    data = models.DateTimeField(auto_now_add=True)
    chat = models.ForeignKey(chat, on_delete=models.CASCADE)
    remetente = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['data']

    def __str__(self):
        return self.mensagem

nc/views.py
import os
from pathlib import Path
from django.shortcuts import *
from django.views import View
from django.contrib import messages
from .models import *
from django.contrib.auth import *
from .models import usuario
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
class cadastrousuario(View):
    def get(self, request):
        return render(request, 'site/cadastro/cad.html')
    
    def post(self, request):
        nome = request.POST.get('nome')
        cpf = request.POST.get('cpf')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        telefone = request.POST.get('telefone')
        logradouro = request.POST.get('logradouro')
        numero = request.POST.get('numero')
        bairro = request.POST.get('bairro')
        cidade = request.POST.get('cidade')
        estado = request.POST.get('estado')
        cep = request.POST.get('cep')
        complemento = request.POST.get('complemento')

        try:
            clin = clinica.objects.get(email=email, senha=senha)
            if clin:
                messages.error(request, 'Usuário já cadastrado como clínica')
                return render(request, 'site/cadastro/cad.html')
        except:
            try:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Email já está cadastrado.')
                    return render(request, 'site/cadastro/cad.html')
                else:
                    user = User.objects.create_user(
                    username=nome,
                    email=email,
                    first_name=nome,
                    password=senha
                    )
                    user.save()

                end = endereco.objects.create(logradouro=logradouro, numero=numero, bairro=bairro, cidade=cidade, estado=estado, cep=cep, complemento=complemento)
                usu = usuario.objects.create(nome=nome, email=email, senha=senha, telefone=telefone, endereco=end, user=user, cpf=cpf)
                messages.success(request, 'Usuário cadastrado com sucesso')
                user = authenticate(request, username=usu.nome, password=senha)
                login(request, user)
                return render(request, 'site/menu/menu.html')
            except Exception as e:
                messages.error(request, f'Erro ao cadastrar usuário{e}')
                return render(request, 'site/cadastro/cad.html')
            
class logusuario(View):
    def get(self, request):
        return render(request, 'site/login/log.html')
    
    def post(self, request):
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        
        try:
            usu = usuario.objects.get(email=email, senha=senha)
            user = authenticate(request, username=usu.nome, password=senha)
            if user:
                login(request, user)
        except:
            messages.error(request, 'Usuário não encontrado')
            return render(request, 'site/login/log.html')
        return redirect('menu')

class cadastroclinica(View):
    def get(self, request):
        return render(request, 'site/cadastro/cad.html')
    
    def post(self, request):
        nome = request.POST.get('nome')
        cnpj = request.POST.get('cnpj')
        telefone = request.POST.get('telefone')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        logradouro = request.POST.get('logradouro')
        numero = request.POST.get('numero')
        bairro = request.POST.get('bairro')
        cidade = request.POST.get('cidade')
        estado = request.POST.get('estado')
        cep = request.POST.get('cep')
        complemento = request.POST.get('complemento')

        try:
            user = usuario.objects.get(email=email, senha=senha)
            if user:
                messages.error(request, 'Clínica já cadastrado como usuário')
            return render(request, 'site/cadastro/cad.html')
        except:
            try:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Email já está cadastrado.')
                    return render(request, 'site/cadastro/cad.html')
                else:
                    user = User.objects.create_user(
                    username=nome,
                    email=email,
                    first_name=nome,
                    password=senha
                    )
                    user.save()

                end = endereco.objects.create(logradouro=logradouro, numero=numero, bairro=bairro, cidade=cidade, estado=estado, cep=cep, complemento=complemento)
                clin = clinica.objects.create(nome=nome, cnpj=cnpj, telefone=telefone, email=email, senha=senha, endereco=end, user=user)
                messages.success(request, 'Clínica cadastrado com sucesso')
                user = authenticate(request, username=clin.nome, password=senha)
                login(request, user)
                return redirect('clined')
            except Exception as e:
                messages.error(request, f'Erro ao cadastrar clínica - {e}')
                return render(request, 'site/cadastro/cad.html')
           
    
class logclinica(View):
    def get(self, request):
        return render(request, 'site/login/log.html')
    
    def post(self, request):
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        
        try:
            usu = clinica.objects.get(email=email, senha=senha)
            user = authenticate(request, username=usu.nome, password=senha)
            if user:
                login(request, user)
        except:
            messages.error(request, 'Clínica não encontrada')
            return render(request, 'site/login/log.html')
        return redirect('clinc')

class logoutu(View):
    def get(self, request):
        logout(request)
        return render(request, 'site/login/log.html')

class menu(View):
    def get(self, request):
        if request.user.is_authenticated:
            hist = historico.objects.filter(usuario=request.user.usuario)
            return render(request, 'site/menu/menu.html', {"hist_usu": hist})
        else:
            return render(request, 'site/menu/menu.html')
    
    def post(self, request):
        try:
            clin = clinica.objects.get(nome=request.POST.get('pesqi'))
            if clin == clinica.objects.get(nome=clin.nome):
                hist = historico.objects.filter(usuario=request.user.usuario)
                if hist.count() == 3:
                    hist.first().delete()
                historico.objects.create(clinica=clin, usuario=request.user.usuario)
                hist = historico.objects.filter(usuario=request.user.usuario)
                return render(request, 'site/menu/menu.html', {"clinica": clin, "hist_usu": hist})
        except Exception as e:
            messages.error(request, f'Clínica não encontrada{e}')
            return render(request, 'site/menu/menu.html')
        

class mudar_senha_clin(View):
    def get(self, request):
        return render(request, 'site/senha/sen.html')
    
    def post(self, request):
        try:
            clin = clinica.objects.get(email=request.POST.get('email'))
            if request.POST.get('nsenha') == request.POST.get('csenha'):
                # breakpoint()
                clin.senha = request.POST.get('csenha')
                clin.save()
                return render(request, 'site/login/log.html')
            else:
                messages.error(request, 'As senhas tem que ser iguais')
                return render(request, 'site/senha/sen.html')
        except:
            messages.error(request, 'Clínica não encontrada')
            return render(request, 'site/senha/sen.html')

class perfil(View):
    def get(self, request):
        fav = favorito.objects.filter(usuario=request.user.usuario)
        return render(request, 'site/perfil/perfil.html', {"favo": fav})
    
    def post(self, request):
        try:
            usu = request.user.usuario
            nome = request.POST.get('nome')
            telefone = request.POST.get('telefone')
            cpf = request.POST.get('cpf')
            email = request.POST.get('email')
            logradouro = request.POST.get('logradouro')
            numero = request.POST.get('numero')
            complemento = request.POST.get('complemento')
            cep = request.POST.get('cep')
            bairro = request.POST.get('bairro')
            cidade = request.POST.get('cidade')
            estado = request.POST.get('estado')
            usu.nome = nome
            usu.telefone = telefone
            usu.cpf = cpf
            usu.email = email
            usu.endereco.logradouro = logradouro
            usu.endereco.numero = numero
            usu.endereco.complemento = complemento
            usu.endereco.cep = cep
            usu.endereco.bairro = bairro
            usu.endereco.cidade = cidade
            usu.endereco.estado = estado
            usu.endereco.save()
            usu.save()
            messages.success(request, "Dados atualizados!")
            return redirect('perfil')
        except:
            messages.error(request, "Erro ao atualizar dados")
            return redirect('perfil')

class resultados(View):
    def get(self, request):
        return render(request, 'site/pesquisa/pesq.html', {"esp": especialidades.objects.all(), "plan": plano.objects.all()})
    
    def post(self, request):
        mens = ''
        i = request.POST.get("pesqi")
        p = request.POST.get("plan")
        e = request.POST.get("esp")
        respe = clinica.objects.filter(plano=p, especialidades=e)
        resp = clinica.objects.filter(plano__in=plano.objects.filter(id=p))
        rese = clinica.objects.filter(especialidades__in=especialidades.objects.filter(id=e))
        resi = clinica.objects.filter(nome=i)

nc/templates/site/chat/chatclin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clínica</title>
    <link rel="stylesheet" href="{% static 'chatclin_est.css' %}">
</head>

<body>
    <header class="header">
        <div class="logo"><a href="{% url 'clinc' %}">natal<span>care</span></a></div>
        <span id="prfl-login">
            {% if request.user.clinica %}
                <button class="login-button" id="usu">{{request.user.clinica}}</button>
                <div class="menu-panel" id="menuPanel">
                    <section id="menuh">
                        <a href="{% url 'clinc' %}">
                            <section id="opc"><h4>Menu</h4></section>
                        </a>
                        <a href="{% url 'clined' %}">
                            <section id="opc"><h4>Perfil</h4></section>
                        </a>
                        <a href="{% url 'chatclin' %}">
                            <section id="opc"><h4>Agendamento</h4></section>
                        </a>
                        <a href="{% url 'logoutu' %}">
                            <section id="opc"><h4>Sair</h4></section>
                        </a>
                    </section>
                </div>
                <button class="menu-button" onclick="toggleMenuPanel()"><img src="{% static 'imagens_site/menu-img.png' %}" alt="" height="50px" width="50px"></button>
            {% endif %}
        </span>
    </header>

    <main>
        {% if conv_iniciada %}
            <section id="conversas">
                <h1>Conversas</h1>

                {% for i in conv_iniciada %}
                    <a href="{% url 'prochatclin' i.usuario.id %}" id="convs">
                        <h2>{{i.usuario.nome}}</h2>
                    </a>
                {% endfor %}

            </section>

            {% if conversa %}
                <section id="chat">
                    <section id="nome-clin">
                        <h1>{{conversa.usuario.nome}}</h1>
                    </section>

                    <section id="area-chat">
                        {% for i in conversa.mensagens_set.all %}
                            {% if i.remetente.username == request.user.clinica.nome %}
                                <section id="clinmen"><p id="clinmens">{{i.mensagem}}</p></section>
                            {% else %}
                                <section id="usumen"><p id="usumens">{{i.mensagem}}</p></section>
                            {% endif %}
                        {% endfor %}
                    </section>

                    <form id="digitex" action="{% url 'prochatclin' conversa.usuario.id %}" method="POST">
                        {% csrf_token %}
                        <input type="text" name="mens" id="" placeholder="Digite sua mensagem...">
                        <input type="submit" name="" id="">
                    </form>
                </section>
            {% endif %}
        {% else %}
            <p id="nao-conv">Clínica não possui conversas de agendamento</p>
        {% endif %}
    </main>

    <footer class="footer">
        <div class="footer-menu">
            <ul>
                <li><strong>Início</strong><br>Home<br>Login<br>Cadastro</li>
                <li><strong>Sobre nós</strong><br>Informações<br>Contato</li>
                <li><strong>Suporte</strong><br>FAQ<br>Chat</li>
            </ul>
        </div>
        <div class="footer-logo">
            <p class="brand-name">natalcare</p>
            <p class="brand-slogan">Sua pesquisa acaba aqui!</p>
        </div>
        <div class="footer-social">
            <!-- LinkedIn SVG -->
            <a href="#" title="LinkedIn">
                <img src="{% static 'imagens_site/linkedin.svg' %}" alt="">
            </a>
            <!-- Instagram SVG -->
            <a href="#" title="Instagram">
                <img src="{% static 'imagens_site/instagram.svg' %}" alt="">
            </a>
            <!-- Facebook SVG -->
            <a href="#" title="Facebook">
                <img src="{% static 'imagens_site/facebook.svg' %}" alt="">
            </a>
            <!-- Twitter SVG -->
            <a href="#" title="Twitter">
                <img src="{% static 'imagens_site/x.svg' %}" alt="">
            </a>
        </div>
    </footer>


    <script>
        function toggleMenuPanel() {
            var panel = document.getElementById("menuPanel");
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        }
    </script>
</body>
</html>

nc/templates/site/chat/chatusu.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clínica</title>
    <link rel="stylesheet" href="{% static 'chatusu_est.css' %}">
</head>

<body>
    <header class="header">
        <div class="logo"><a href="{% url 'menu' %}">natal<span>care</span></a></div>
        <a href="{% url 'pesq' %}"><input type="text" placeholder="Digite o nome da clínica:" class="search-input"></a>
        <span id="prfl-login">
            {% if request.user.usuario %}
                <button class="login-button" id="usu">{{request.user.usuario}}</button>
                <div class="menu-panel" id="menuPanel">
                    <section id="menuh">
                            <a href="{% url 'menu' %}">
                                <section id="opc"><h4>Menu</h4></section>
                            </a>
                            <a href="{% url 'perfil' %}">
                                <section id="opc"><h4>Perfil</h4></section>
                            </a>
                            <a href="{% url 'pesq' %}">
                                <section id="opc"><h4>Pesquisa</h4></section>
                            </a>
                            <a href="{% url 'chatusu' %}">
                                <section id="opc"><h4>Agendamento</h4></section>
                            </a>
                            <a href="{% url 'logoutu' %}">
                                <section id="opc"><h4>Sair</h4></section>
                            </a>
                    </section>
                </div>
                <button class="menu-button" onclick="toggleMenuPanel()"><img src="{% static 'imagens_site/menu-img.png' %}" alt="" height="50px" width="50px"></button>
            {% endif %}
        </span>
    </header>

    <main>
        {% if conv_iniciada %}
            <section id="conversas">
                <h1>Conversas</h1>

                {% for i in conv_iniciada %}
                    <a href="{% url 'prochatusu' i.clinica.id %}" id="convs">
                        <h2>{{i.clinica.nome}}</h2>
                    </a>
                {% endfor %}

            </section>

            {% if conversa %}
                <section id="chat">
                    <section id="nome-clin">
                        <h1>{{conversa.clinica.nome}}</h1>
                    </section>

                    <section id="area-chat">
                        {% for i in conversa.mensagens_set.all %}
                            {% if i.remetente.username == request.user.usuario.nome %}
                                <section id="clinmen"><p id="clinmens">{{i.mensagem}}</p></section>
                            {% else %}
                                <section id="usumen"><p id="usumens">{{i.mensagem}}</p></section>
                            {% endif %}
                        {% endfor %}
                    </section>

                    <form id="digitex" action="{% url 'prochatusu' conversa.clinica.id  %}" method="POST">
                        {% csrf_token %}
                        <input type="text" name="mens" id="" placeholder="Digite sua mensagem...">
                        <input type="submit" name="" id="">
                    </form>
                </section>
                {% endif %}
        {% else %}
            <section>
                <p id="nao-conv" style="margin-bottom: 10px;">Usuário não possui conversas de agendamento</p>
                <p id="nao-conv">Para iniciar uma conversa de agendamento, entre na página de alguma clínica e clique em "Agendar Consulta"</p>
            </section>
        {% endif %}
    </main>

    <footer class="footer">
        <div class="footer-menu">
            <ul>
                <li><strong>Início</strong><br>Home<br>Login<br>Cadastro</li>
                <li><strong>Sobre nós</strong><br>Informações<br>Contato</li>
                <li><strong>Suporte</strong><br>FAQ<br>Chat</li>
            </ul>
        </div>
        <div class="footer-logo">
            <p class="brand-name">natalcare</p>
            <p class="brand-slogan">Sua pesquisa acaba aqui!</p>
        </div>
        <div class="footer-social">
            <!-- LinkedIn SVG -->
            <a href="#" title="LinkedIn">
                <img src="{% static 'imagens_site/linkedin.svg' %}" alt="">
            </a>
            <!-- Instagram SVG -->
            <a href="#" title="Instagram">
                <img src="{% static 'imagens_site/instagram.svg' %}" alt="">
            </a>
            <!-- Facebook SVG -->
            <a href="#" title="Facebook">
                <img src="{% static 'imagens_site/facebook.svg' %}" alt="">
            </a>
            <!-- Twitter SVG -->
            <a href="#" title="Twitter">
                <img src="{% static 'imagens_site/x.svg' %}" alt="">
            </a>
        </div>
    </footer>


    <script>

        function toggleMenuPanel() {
            var panel = document.getElementById("menuPanel");
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        }
    </script>
</body>
</html>